/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SimulacoesRouteImport } from './routes/simulacoes'
import { Route as RegrasRouteImport } from './routes/regras'
import { Route as RankingIasRouteImport } from './routes/ranking-ias'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as MataMataRouteImport } from './routes/mata-mata'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as HallDaFamaRouteImport } from './routes/hall-da-fama'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as ConsensoRouteImport } from './routes/consenso'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelecoesIndexRouteImport } from './routes/selecoes.index'
import { Route as SelecoesIdRouteImport } from './routes/selecoes.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacoesRoute = SimulacoesRouteImport.update({
  id: '/simulacoes',
  path: '/simulacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasRoute = RegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIasRoute = RankingIasRouteImport.update({
  id: '/ranking-ias',
  path: '/ranking-ias',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const MataMataRoute = MataMataRouteImport.update({
  id: '/mata-mata',
  path: '/mata-mata',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const HallDaFamaRoute = HallDaFamaRouteImport.update({
  id: '/hall-da-fama',
  path: '/hall-da-fama',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsensoRoute = ConsensoRouteImport.update({
  id: '/consenso',
  path: '/consenso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecoesIndexRoute = SelecoesIndexRouteImport.update({
  id: '/selecoes/',
  path: '/selecoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecoesIdRoute = SelecoesIdRouteImport.update({
  id: '/selecoes/$id',
  path: '/selecoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consenso': typeof ConsensoRoute
  '/grupos': typeof GruposRoute
  '/hall-da-fama': typeof HallDaFamaRoute
  '/jogos': typeof JogosRoute
  '/mata-mata': typeof MataMataRoute
  '/metodologia': typeof MetodologiaRoute
  '/ranking-ias': typeof RankingIasRoute
  '/regras': typeof RegrasRoute
  '/simulacoes': typeof SimulacoesRoute
  '/sobre': typeof SobreRoute
  '/selecoes/$id': typeof SelecoesIdRoute
  '/selecoes/': typeof SelecoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consenso': typeof ConsensoRoute
  '/grupos': typeof GruposRoute
  '/hall-da-fama': typeof HallDaFamaRoute
  '/jogos': typeof JogosRoute
  '/mata-mata': typeof MataMataRoute
  '/metodologia': typeof MetodologiaRoute
  '/ranking-ias': typeof RankingIasRoute
  '/regras': typeof RegrasRoute
  '/simulacoes': typeof SimulacoesRoute
  '/sobre': typeof SobreRoute
  '/selecoes/$id': typeof SelecoesIdRoute
  '/selecoes': typeof SelecoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consenso': typeof ConsensoRoute
  '/grupos': typeof GruposRoute
  '/hall-da-fama': typeof HallDaFamaRoute
  '/jogos': typeof JogosRoute
  '/mata-mata': typeof MataMataRoute
  '/metodologia': typeof MetodologiaRoute
  '/ranking-ias': typeof RankingIasRoute
  '/regras': typeof RegrasRoute
  '/simulacoes': typeof SimulacoesRoute
  '/sobre': typeof SobreRoute
  '/selecoes/$id': typeof SelecoesIdRoute
  '/selecoes/': typeof SelecoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consenso'
    | '/grupos'
    | '/hall-da-fama'
    | '/jogos'
    | '/mata-mata'
    | '/metodologia'
    | '/ranking-ias'
    | '/regras'
    | '/simulacoes'
    | '/sobre'
    | '/selecoes/$id'
    | '/selecoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consenso'
    | '/grupos'
    | '/hall-da-fama'
    | '/jogos'
    | '/mata-mata'
    | '/metodologia'
    | '/ranking-ias'
    | '/regras'
    | '/simulacoes'
    | '/sobre'
    | '/selecoes/$id'
    | '/selecoes'
  id:
    | '__root__'
    | '/'
    | '/consenso'
    | '/grupos'
    | '/hall-da-fama'
    | '/jogos'
    | '/mata-mata'
    | '/metodologia'
    | '/ranking-ias'
    | '/regras'
    | '/simulacoes'
    | '/sobre'
    | '/selecoes/$id'
    | '/selecoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsensoRoute: typeof ConsensoRoute
  GruposRoute: typeof GruposRoute
  HallDaFamaRoute: typeof HallDaFamaRoute
  JogosRoute: typeof JogosRoute
  MataMataRoute: typeof MataMataRoute
  MetodologiaRoute: typeof MetodologiaRoute
  RankingIasRoute: typeof RankingIasRoute
  RegrasRoute: typeof RegrasRoute
  SimulacoesRoute: typeof SimulacoesRoute
  SobreRoute: typeof SobreRoute
  SelecoesIdRoute: typeof SelecoesIdRoute
  SelecoesIndexRoute: typeof SelecoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacoes': {
      id: '/simulacoes'
      path: '/simulacoes'
      fullPath: '/simulacoes'
      preLoaderRoute: typeof SimulacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras': {
      id: '/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof RegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking-ias': {
      id: '/ranking-ias'
      path: '/ranking-ias'
      fullPath: '/ranking-ias'
      preLoaderRoute: typeof RankingIasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mata-mata': {
      id: '/mata-mata'
      path: '/mata-mata'
      fullPath: '/mata-mata'
      preLoaderRoute: typeof MataMataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-da-fama': {
      id: '/hall-da-fama'
      path: '/hall-da-fama'
      fullPath: '/hall-da-fama'
      preLoaderRoute: typeof HallDaFamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consenso': {
      id: '/consenso'
      path: '/consenso'
      fullPath: '/consenso'
      preLoaderRoute: typeof ConsensoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consenso': {
      id: '/consenso'
      path: '/consenso'
      fullPath: '/consenso'
      preLoaderRoute: typeof ConsensoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecoes/': {
      id: '/selecoes/'
      path: '/selecoes'
      fullPath: '/selecoes/'
      preLoaderRoute: typeof SelecoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecoes/$id': {
      id: '/selecoes/$id'
      path: '/selecoes/$id'
      fullPath: '/selecoes/$id'
      preLoaderRoute: typeof SelecoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsensoRoute: ConsensoRoute,
  GruposRoute: GruposRoute,
  HallDaFamaRoute: HallDaFamaRoute,
  JogosRoute: JogosRoute,
  MataMataRoute: MataMataRoute,
  MetodologiaRoute: MetodologiaRoute,
  RankingIasRoute: RankingIasRoute,
  RegrasRoute: RegrasRoute,
  SimulacoesRoute: SimulacoesRoute,
  SobreRoute: SobreRoute,
  SelecoesIdRoute: SelecoesIdRoute,
  SelecoesIndexRoute: SelecoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
