/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SimulacoesRouteImport } from './routes/simulacoes'
import { Route as RegrasRouteImport } from './routes/regras'
import { Route as RankingIasRouteImport } from './routes/ranking-ias'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MataMataRouteImport } from './routes/mata-mata'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as HallDaFamaRouteImport } from './routes/hall-da-fama'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as EscalacoesRouteImport } from './routes/escalacoes'
import { Route as ConsensoRouteImport } from './routes/consenso'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelecoesIndexRouteImport } from './routes/selecoes.index'
import { Route as SelecoesIdRouteImport } from './routes/selecoes.$id'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacoesRoute = SimulacoesRouteImport.update({
  id: '/simulacoes',
  path: '/simulacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasRoute = RegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIasRoute = RankingIasRouteImport.update({
  id: '/ranking-ias',
  path: '/ranking-ias',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MataMataRoute = MataMataRouteImport.update({
  id: '/mata-mata',
  path: '/mata-mata',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const HallDaFamaRoute = HallDaFamaRouteImport.update({
  id: '/hall-da-fama',
  path: '/hall-da-fama',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalacoesRoute = EscalacoesRouteImport.update({
  id: '/escalacoes',
  path: '/escalacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsensoRoute = ConsensoRouteImport.update({
  id: '/consenso',
  path: '/consenso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecoesIndexRoute = SelecoesIndexRouteImport.update({
  id: '/selecoes/',
  path: '/selecoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecoesIdRoute = SelecoesIdRouteImport.update({
  id: '/selecoes/$id',
  path: '/selecoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consenso': typeof ConsensoRoute
  '/escalacoes': typeof EscalacoesRoute
  '/grupos': typeof GruposRoute
  '/hall-da-fama': typeof HallDaFamaRoute
  '/jogos': typeof JogosRoute
  '/mata-mata': typeof MataMataRoute
  '/mcp': typeof McpRoute
  '/metodologia': typeof MetodologiaRoute
  '/ranking-ias': typeof RankingIasRoute
  '/regras': typeof RegrasRoute
  '/simulacoes': typeof SimulacoesRoute
  '/sobre': typeof SobreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/match/$id': typeof MatchIdRoute
  '/selecoes/$id': typeof SelecoesIdRoute
  '/selecoes/': typeof SelecoesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consenso': typeof ConsensoRoute
  '/escalacoes': typeof EscalacoesRoute
  '/grupos': typeof GruposRoute
  '/hall-da-fama': typeof HallDaFamaRoute
  '/jogos': typeof JogosRoute
  '/mata-mata': typeof MataMataRoute
  '/mcp': typeof McpRoute
  '/metodologia': typeof MetodologiaRoute
  '/ranking-ias': typeof RankingIasRoute
  '/regras': typeof RegrasRoute
  '/simulacoes': typeof SimulacoesRoute
  '/sobre': typeof SobreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/match/$id': typeof MatchIdRoute
  '/selecoes/$id': typeof SelecoesIdRoute
  '/selecoes': typeof SelecoesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consenso': typeof ConsensoRoute
  '/escalacoes': typeof EscalacoesRoute
  '/grupos': typeof GruposRoute
  '/hall-da-fama': typeof HallDaFamaRoute
  '/jogos': typeof JogosRoute
  '/mata-mata': typeof MataMataRoute
  '/mcp': typeof McpRoute
  '/metodologia': typeof MetodologiaRoute
  '/ranking-ias': typeof RankingIasRoute
  '/regras': typeof RegrasRoute
  '/simulacoes': typeof SimulacoesRoute
  '/sobre': typeof SobreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/match/$id': typeof MatchIdRoute
  '/selecoes/$id': typeof SelecoesIdRoute
  '/selecoes/': typeof SelecoesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consenso'
    | '/escalacoes'
    | '/grupos'
    | '/hall-da-fama'
    | '/jogos'
    | '/mata-mata'
    | '/mcp'
    | '/metodologia'
    | '/ranking-ias'
    | '/regras'
    | '/simulacoes'
    | '/sobre'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/match/$id'
    | '/selecoes/$id'
    | '/selecoes/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consenso'
    | '/escalacoes'
    | '/grupos'
    | '/hall-da-fama'
    | '/jogos'
    | '/mata-mata'
    | '/mcp'
    | '/metodologia'
    | '/ranking-ias'
    | '/regras'
    | '/simulacoes'
    | '/sobre'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/match/$id'
    | '/selecoes/$id'
    | '/selecoes'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/consenso'
    | '/escalacoes'
    | '/grupos'
    | '/hall-da-fama'
    | '/jogos'
    | '/mata-mata'
    | '/mcp'
    | '/metodologia'
    | '/ranking-ias'
    | '/regras'
    | '/simulacoes'
    | '/sobre'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/match/$id'
    | '/selecoes/$id'
    | '/selecoes/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsensoRoute: typeof ConsensoRoute
  EscalacoesRoute: typeof EscalacoesRoute
  GruposRoute: typeof GruposRoute
  HallDaFamaRoute: typeof HallDaFamaRoute
  JogosRoute: typeof JogosRoute
  MataMataRoute: typeof MataMataRoute
  McpRoute: typeof McpRoute
  MetodologiaRoute: typeof MetodologiaRoute
  RankingIasRoute: typeof RankingIasRoute
  RegrasRoute: typeof RegrasRoute
  SimulacoesRoute: typeof SimulacoesRoute
  SobreRoute: typeof SobreRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  MatchIdRoute: typeof MatchIdRoute
  SelecoesIdRoute: typeof SelecoesIdRoute
  SelecoesIndexRoute: typeof SelecoesIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacoes': {
      id: '/simulacoes'
      path: '/simulacoes'
      fullPath: '/simulacoes'
      preLoaderRoute: typeof SimulacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras': {
      id: '/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof RegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking-ias': {
      id: '/ranking-ias'
      path: '/ranking-ias'
      fullPath: '/ranking-ias'
      preLoaderRoute: typeof RankingIasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mata-mata': {
      id: '/mata-mata'
      path: '/mata-mata'
      fullPath: '/mata-mata'
      preLoaderRoute: typeof MataMataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-da-fama': {
      id: '/hall-da-fama'
      path: '/hall-da-fama'
      fullPath: '/hall-da-fama'
      preLoaderRoute: typeof HallDaFamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalacoes': {
      id: '/escalacoes'
      path: '/escalacoes'
      fullPath: '/escalacoes'
      preLoaderRoute: typeof EscalacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consenso': {
      id: '/consenso'
      path: '/consenso'
      fullPath: '/consenso'
      preLoaderRoute: typeof ConsensoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecoes/': {
      id: '/selecoes/'
      path: '/selecoes'
      fullPath: '/selecoes/'
      preLoaderRoute: typeof SelecoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecoes/$id': {
      id: '/selecoes/$id'
      path: '/selecoes/$id'
      fullPath: '/selecoes/$id'
      preLoaderRoute: typeof SelecoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsensoRoute: ConsensoRoute,
  EscalacoesRoute: EscalacoesRoute,
  GruposRoute: GruposRoute,
  HallDaFamaRoute: HallDaFamaRoute,
  JogosRoute: JogosRoute,
  MataMataRoute: MataMataRoute,
  McpRoute: McpRoute,
  MetodologiaRoute: MetodologiaRoute,
  RankingIasRoute: RankingIasRoute,
  RegrasRoute: RegrasRoute,
  SimulacoesRoute: SimulacoesRoute,
  SobreRoute: SobreRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  MatchIdRoute: MatchIdRoute,
  SelecoesIdRoute: SelecoesIdRoute,
  SelecoesIndexRoute: SelecoesIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
